### ISSUE TITLE
仓储 DeleteAsync提示错误

### ISSUE THREAD

**Issue by rex19001** [2881099/FreeSql.Wiki.VuePress#17]
`// 这个不能删除`
` public async Task BatchDeleted(List<IdDto> idDtos)` 
`{`
`    // 这个返回的是 IEnumerable<Account>`
     ` var ids = idDtos.Select(s => new AccountEntity() { Id = s.Id });`
    `  await _repository.DeleteAsync(ids);`
  `}`
`// 这个可以`
` public async Task BatchDeleted(List<IdDto> idDtos)`
  `{`
`    // 这个返回的是 List<Account>`
`      var ids = idDtos.Select(s => new AccountEntity() { Id = s.Id }).ToList();`
`      await _repository.DeleteAsync(ids);`
  `}`

而源码里要求传的也是IEnumerable， 所以这里有点误导人了 ，并且不报异常
`
 Task<int> DeleteAsync(IEnumerable<TEntity> entitys, CancellationToken cancellationToken = default (CancellationToken));
`

**Comment by zhontai** [comment]
var orgs = input.Staff.OrgIds.Select(orgId => new StaffOrgEntity
{
    StaffId = staff.Id,
    OrgId = orgId
});
await _staffOrgRepository.InsertAsync(orgs);
1条数据正常获取到审计数据Id值，
2条数据，进入审计数据正常，插入Id值为0，无法插入。

var orgs = input.Staff.OrgIds.Select(orgId => new StaffOrgEntity
{
    StaffId = staff.Id,
    OrgId = orgId
}).ToList();
await _staffOrgRepository.InsertAsync(orgs);
2条数据可正常插入。
