### ISSUE TITLE
oracle 没有参数化前缀

### ISSUE THREAD

**Issue by hjkl950217** [2881099/FreeSql.Wiki.VuePress#36]
文档这里写到oracle时，是空的。可能是写漏了？或是现在不支持哇
https://github.com/2881099/FreeSql.Wiki.VuePress/blob/main/docs/guide/ado.md?plain=1#L31

**Comment by luoyunchong** [comment]
就是冒号：

**Comment by hjkl950217** [comment]
正好有个PR，我一起优化下表达吧  PR：#35
