### ISSUE TITLE
分页查询的问题

### ISSUE THREAD

**Issue by id270** [2881099/FreeSql.Wiki.VuePress#43]
我发现如果使用分页查询，最后一页不满的情况下，查询出来的结果是满屏数据，例如 我现在31条数据，每页10条，他会分出4页，我在查第四页的时候传值是 page(4,10) 他会查出来10条数据
程序集 FreeSql, Version=3.2.833.0

**Comment by 2881099** [comment]
具体要监视 SQL，把 SQL 拉到数据库上执行。
